// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package mzuriheallth

import (
	"fmt"
	"io"
	"strconv"
)

type Allergy struct {
	Allergytype *string   `json:"allergytype"`
	Detail      *string   `json:"detail"`
	Metadata    *Metadata `json:"metadata"`
}

type Condition struct {
	Conditiontype *string   `json:"conditiontype"`
	Detail        *string   `json:"detail"`
	Metadata      *Metadata `json:"metadata"`
}

type HospFile struct {
	ID         string  `json:"id"`
	Date       int     `json:"date"`
	Lastvisit  int     `json:"lastvisit"`
	No         string  `json:"no"`
	Idno       *string `json:"idno"`
	Visitcount *int    `json:"visitcount"`
}

type Insurance struct {
	ID          string  `json:"id"`
	Insuranceno *string `json:"insuranceno"`
}

type Medicalinfo struct {
	Bloodtype  *string      `json:"bloodtype"`
	Conditions []*Condition `json:"conditions"`
	Allergies  []*Allergy   `json:"allergies"`
	Vitals     *Vitals      `json:"vitals"`
	Metadata   *Metadata    `json:"metadata"`
}

type Metadata struct {
	Date     *int `json:"date"`
	Lastedit *int `json:"lastedit"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Nextofkin struct {
	Name         *string `json:"name"`
	Relationship *string `json:"relationship"`
	Phone        *string `json:"phone"`
	Workplace    *string `json:"workplace"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Vitals struct {
	Height      *int    `json:"height"`
	Weight      *int    `json:"weight"`
	Pressure    *int    `json:"pressure"`
	Sugar       *int    `json:"sugar"`
	Heartrate   *int    `json:"heartrate"`
	Respiration *int    `json:"respiration"`
	Hb          *string `json:"hb"`
}

type NewPatient string

const (
	NewPatientPatient NewPatient = "Patient"
)

var AllNewPatient = []NewPatient{
	NewPatientPatient,
}

func (e NewPatient) IsValid() bool {
	switch e {
	case NewPatientPatient:
		return true
	}
	return false
}

func (e NewPatient) String() string {
	return string(e)
}

func (e *NewPatient) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NewPatient(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid newPatient", str)
	}
	return nil
}

func (e NewPatient) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
