// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package mzuriheallth

import (
	"fmt"
	"io"
	"strconv"
)

type Location struct {
	Type        GeoType `json:"type"`
	Coordinates []*int  `json:"coordinates"`
}

type GeoType string

const (
	GeoTypePolygon GeoType = "Polygon"
	GeoTypePoint   GeoType = "Point"
)

var AllGeoType = []GeoType{
	GeoTypePolygon,
	GeoTypePoint,
}

func (e GeoType) IsValid() bool {
	switch e {
	case GeoTypePolygon, GeoTypePoint:
		return true
	}
	return false
}

func (e GeoType) String() string {
	return string(e)
}

func (e *GeoType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GeoType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid geoType", str)
	}
	return nil
}

func (e GeoType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type NewPatient string

const (
	NewPatientPatient NewPatient = "Patient"
)

var AllNewPatient = []NewPatient{
	NewPatientPatient,
}

func (e NewPatient) IsValid() bool {
	switch e {
	case NewPatientPatient:
		return true
	}
	return false
}

func (e NewPatient) String() string {
	return string(e)
}

func (e *NewPatient) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NewPatient(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid newPatient", str)
	}
	return nil
}

func (e NewPatient) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
