# https://gqlgen.com/getting-started/
# import everything to everything so that all models can interact with each other with little effort
# Import * from "/**/*.graphql"

type Subscription {
	queueChanged(id: ID!): Patient!
	userChanged(id: ID!): HospAdmin!
	hospChanged(id: ID): Hospital!
	patientChanged(id: ID): Patient!
	procedureChanged(id: ID): RawProcedure!
}

type Query {
	Patient(id: ID!): [Patient!]
	PatientNotes(patientid: ID!, from: Int, to: Int): [PatientNote]
	HospAdmin(id: ID!): HospAdmin
	AdminCategories: [AdminCategory]!
	Hospital(id: ID!): Hospital
	HospFile(id: ID): HospFile
	AllInsurance: [Insurance]!
	PaymentChannels(hospitalid: ID!): [PaymentChannel]!
	AllPaymentMethods: [PaymentMethod]!
}

type Mutation {
	createPatient(input: NewPatient!): Patient!
	createAdmin(input: NewAdmin): HospAdmin!
}

schema {
	query: Query
	mutation: Mutation
}
