
# https://gqlgen.com/getting-started/

# Import Patient from "patient.graphql"

enum geoType {
	Polygon
	Point
}
type location{
	type: geoType!
	coordinates: [Int]!
}

type Subscription {
	queueChanged(id: ID!): Patient!
	userChanged(id : ID!) : HospAdmin!
	hospChanged(id : ID) : Hospital!
	patientChanged(id : ID) : Patient!
	procedureChanged(id : ID): RawProcedure!
}

type HospFile {
	id: ID!
	date: Int!
	lastvisit: Int!
	no: String!
	idno: String
	visitcount: Int
}
type Hospital {
	id: ID!
	location: location!
	name: String!
}

type RawProcedure {
	name: String!
}
type Insurance {
	id: String!
	insuranceno: String
}

type Nextofkin {
	name: String
	relationship: String
	phone: String
	workplace: String
}

type Medicalinfo {
	bloodtype: String
	conditions: [Condition]
	allergies: [Allergy]
	vitals: Vitals
	metadata: Metadata
}

type Condition {
	conditiontype: String
	detail: String
	metadata: Metadata
}

type Allergy {
	allergytype: String
	detail: String
	metadata: Metadata
}

type Vitals {
	height: Int
	weight: Int
	pressure: Int
	sugar: Int
	heartrate: Int
	respiration: Int
	hb: String
}

type Metadata {
	date: Int
	lastedit: Int
}


type Query {
	Patient(id: ID!): [Patient!]!
	HospAdmin(id: ID!): [HospAdmin!]!
}


type Mutation {
	createPatient(input: newPatient!): Patient!
}

schema {
	query: Query
	mutation: Mutation
}
