# Import * from "../**/*.graphql"

type HospAdmin {
	Id: ID!
	status: Boolean!
	data: data!
	config: config!
	profiledata: profiledata!
	metadata: Metadata!
}
input newHospAdmin {
	email: String!
}

type data {
	uid: String!
	email: String!
	photoURL: String!
	displayName: String!
}

type config {
	hospitalId: String!
	categoryId: String!
	level: Int!
	availability: Int! # Whether on break , away or available
}

type profiledata {
	bio: String!
	age: String!
	address: String!
	phone: String!
	status: Boolean!
}
