# Import * from "../**/*.graphql"

type HospAdmin {
	Id: ID!
	status: Boolean!
	data: Data!
	config: Config!
	profileData: Profiledata!
	metadata: Metadata!
	authdata: Authdata!
}

enum NewAdmin {
	Authdata
}

type Authdata {
	name: String!
	pass: String!
	new: Boolean!
}
type Data {
	uid: String!
	email: String!
	photoURL: String!
	displayName: String!
}

type Config {
	hospitalId: String!
	categoryId: String!
	level: Int!
	availability: Int! # Whether on break , away or available
}

type Profiledata {
	bio: String!
	age: String!
	address: String!
	phone: String!
	status: Boolean!
}

