// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"fmt"
	"io"
	"strconv"
)

type Allergy struct {
	Allergytype *string   `json:"allergytype"`
	Detail      *string   `json:"detail"`
	Metadata    *Metadata `json:"metadata"`
}

type Condition struct {
	Conditiontype *string   `json:"conditiontype"`
	Detail        *string   `json:"detail"`
	Metadata      *Metadata `json:"metadata"`
}

type HospAdmin struct {
	_id  string `json:"_id"`
	Name string `json:"name"`
}

type HospFile struct {
	ID         string  `json:"id"`
	Date       int     `json:"date"`
	Lastvisit  int     `json:"lastvisit"`
	No         string  `json:"no"`
	Idno       *string `json:"idno"`
	Visitcount *int    `json:"visitcount"`
}

type Hospital struct {
	ID       string    `json:"id"`
	Location *Location `json:"location"`
	Name     string    `json:"name"`
}

type Insurance struct {
	ID          string  `json:"id"`
	Insuranceno *string `json:"insuranceno"`
}

type Medicalinfo struct {
	Bloodtype  *string      `json:"bloodtype"`
	Conditions []*Condition `json:"conditions"`
	Allergies  []*Allergy   `json:"allergies"`
	Vitals     *Vitals      `json:"vitals"`
	Metadata   *Metadata    `json:"metadata"`
}

type Metadata struct {
	Date     *int `json:"date"`
	Lastedit *int `json:"lastedit"`
}

type Nextofkin struct {
	Name         *string `json:"name"`
	Relationship *string `json:"relationship"`
	Phone        *string `json:"phone"`
	Workplace    *string `json:"workplace"`
}

type Patient struct {
	Personalinfo string       `json:"personalinfo"`
	Fileinfo     *HospFile    `json:"fileinfo"`
	Done         bool         `json:"done"`
	HospAdmin    *HospAdmin   `json:"HospAdmin"`
	ID           string       `json:"id"`
	Parentid     *string      `json:"parentid"`
	Nextofkin    *Nextofkin   `json:"nextofkin"`
	Insurance    []*Insurance `json:"insurance"`
	Medicalinfo  *Medicalinfo `json:"medicalinfo"`
}

type RawProcedure struct {
	Name string `json:"name"`
}

type Vitals struct {
	Height      *int    `json:"height"`
	Weight      *int    `json:"weight"`
	Pressure    *int    `json:"pressure"`
	Sugar       *int    `json:"sugar"`
	Heartrate   *int    `json:"heartrate"`
	Respiration *int    `json:"respiration"`
	Hb          *string `json:"hb"`
}

type Location struct {
	Type        GeoType `json:"type"`
	Coordinates []*int  `json:"coordinates"`
}

type GeoType string

const (
	GeoTypePolygon GeoType = "Polygon"
	GeoTypePoint   GeoType = "Point"
)

var AllGeoType = []GeoType{
	GeoTypePolygon,
	GeoTypePoint,
}

func (e GeoType) IsValid() bool {
	switch e {
	case GeoTypePolygon, GeoTypePoint:
		return true
	}
	return false
}

func (e GeoType) String() string {
	return string(e)
}

func (e *GeoType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GeoType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid geoType", str)
	}
	return nil
}

func (e GeoType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type NewPatient string

const (
	NewPatientPatient NewPatient = "Patient"
)

var AllNewPatient = []NewPatient{
	NewPatientPatient,
}

func (e NewPatient) IsValid() bool {
	switch e {
	case NewPatientPatient:
		return true
	}
	return false
}

func (e NewPatient) String() string {
	return string(e)
}

func (e *NewPatient) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NewPatient(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid newPatient", str)
	}
	return nil
}

func (e NewPatient) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
