// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"fmt"
	"io"
	"strconv"
)

type AdminInvite struct {
	_id        string    `json:"_id"`
	Name       string    `json:"name"`
	Email      string    `json:"email"`
	Phone      string    `json:"phone"`
	Categoyid  string    `json:"categoyid"`
	Level      int       `json:"level"`
	Inviterid  string    `json:"inviterid"`
	Hospitalid string    `json:"hospitalid"`
	Metadata   *Metadata `json:"metadata"`
}

type Allergy struct {
	Allergytype *string   `json:"allergytype"`
	Detail      *string   `json:"detail"`
	Metadata    *Metadata `json:"metadata"`
}

type Condition struct {
	Conditiontype *string   `json:"conditiontype"`
	Detail        *string   `json:"detail"`
	Metadata      *Metadata `json:"metadata"`
}

type HospAdmin struct {
	_id         string       `json:"_id"`
	Status      bool         `json:"status"`
	Data        *Data        `json:"data"`
	Config      *Config      `json:"config"`
	Profiledata *Profiledata `json:"profiledata"`
	Metadata    *Metadata    `json:"metadata"`
}

type HospFile struct {
	ID         string  `json:"id"`
	Date       int     `json:"date"`
	Lastvisit  int     `json:"lastvisit"`
	No         string  `json:"no"`
	Idno       *string `json:"idno"`
	Visitcount *int    `json:"visitcount"`
}

type Hospital struct {
	Location       *Location        `json:"location"`
	Name           string           `json:"name"`
	Userid         string           `json:"userid"`
	_id            string           `json:"_id"`
	Description    string           `json:"description"`
	Status         *bool            `json:"status"`
	Contactperson  *Contactperson   `json:"contactperson"`
	ContactDetails *ContactDetails  `json:"contactDetails"`
	Logourl        string           `json:"logourl"`
	PatientCount   int              `json:"patientCount"`
	InvoiceCount   int              `json:"invoiceCount"`
	Metadata       *Metadata        `json:"metadata"`
	PaymentMethods []*PaymentMethod `json:"paymentMethods"`
}

type Insurance struct {
	ID          string `json:"id"`
	InsuranceNo string `json:"insuranceNo"`
}

type Medicalinfo struct {
	Bloodtype  *string      `json:"bloodtype"`
	Conditions []*Condition `json:"conditions"`
	Allergies  []*Allergy   `json:"allergies"`
	Vitals     *Vitals      `json:"vitals"`
	Metadata   *Metadata    `json:"metadata"`
}

type Metadata struct {
	Date     *int `json:"date"`
	Lastedit *int `json:"lastedit"`
}

type Nextofkin struct {
	Name         *string `json:"name"`
	Relationship *string `json:"relationship"`
	Phone        *string `json:"phone"`
	Workplace    *string `json:"workplace"`
}

type Patient struct {
	Personalinfo string       `json:"personalinfo"`
	Fileinfo     *HospFile    `json:"fileinfo"`
	Done         bool         `json:"done"`
	HospAdmin    *HospAdmin   `json:"HospAdmin"`
	ID           string       `json:"id"`
	Parentid     *string      `json:"parentid"`
	Nextofkin    *Nextofkin   `json:"nextofkin"`
	Insurance    []*Insurance `json:"insurance"`
	Medicalinfo  *Medicalinfo `json:"medicalinfo"`
}

type PaymentMethod struct {
	AccountNumber    string `json:"accountNumber"`
	ExtraInfo        string `json:"extraInfo"`
	PaymentChannelID string `json:"paymentChannelId"`
	PaymentMethodID  string `json:"paymentMethodId"`
}

type RawProcedure struct {
	Name string `json:"name"`
}

type Vitals struct {
	Height      int    `json:"height"`
	Weight      int    `json:"weight"`
	Pressure    int    `json:"pressure"`
	Sugar       int    `json:"sugar"`
	HeartRate   int    `json:"heartRate"`
	Respiration int    `json:"respiration"`
	Hb          string `json:"hb"`
}

type Config struct {
	HospitalID   string `json:"hospitalId"`
	CategoryID   string `json:"categoryId"`
	Level        int    `json:"level"`
	Availability int    `json:"availability"`
}

type ContactDetails struct {
	Phone   string `json:"phone"`
	Email   string `json:"email"`
	Address string `json:"address"`
}

type Contactperson struct {
	Name     string `json:"name"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
	Position string `json:"position"`
	Address  string `json:"address"`
}

type Data struct {
	UID         string `json:"uid"`
	Email       string `json:"email"`
	PhotoURL    string `json:"photoURL"`
	DisplayName string `json:"displayName"`
}

type Location struct {
	Type        GeoType `json:"type"`
	Coordinates []*int  `json:"coordinates"`
}

type Profiledata struct {
	Bio     string `json:"bio"`
	Age     string `json:"age"`
	Address string `json:"address"`
	Phone   string `json:"phone"`
	Status  bool   `json:"status"`
}

type GeoType string

const (
	GeoTypePolygon GeoType = "Polygon"
	GeoTypePoint   GeoType = "Point"
)

var AllGeoType = []GeoType{
	GeoTypePolygon,
	GeoTypePoint,
}

func (e GeoType) IsValid() bool {
	switch e {
	case GeoTypePolygon, GeoTypePoint:
		return true
	}
	return false
}

func (e GeoType) String() string {
	return string(e)
}

func (e *GeoType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GeoType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid geoType", str)
	}
	return nil
}

func (e GeoType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type NewPatient string

const (
	NewPatientPatient NewPatient = "Patient"
)

var AllNewPatient = []NewPatient{
	NewPatientPatient,
}

func (e NewPatient) IsValid() bool {
	switch e {
	case NewPatientPatient:
		return true
	}
	return false
}

func (e NewPatient) String() string {
	return string(e)
}

func (e *NewPatient) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NewPatient(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid newPatient", str)
	}
	return nil
}

func (e NewPatient) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
